//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int iIdEquipo { get; set; }
        public int iIdMarca { get; set; }
        public int iIdModelo { get; set; }
        public string vchNoSerie { get; set; }
        public Nullable<int> iExistencia { get; set; }
        public int iIdProveedor { get; set; }
        public int iIdAlmacen { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
